stages:
  - build
  - test

build_job:
  stage: build
  image: "ubuntu:latest"
  before_script:
    - apt-get -y -qq update
    - apt-get -y -qq install build-essential mpich mpich-doc libmpich-dev libssl-dev

  script: make build
  tags:
    - shared runner

test_job:
  stage: test
  image: "ubuntu:latest"
  before_script:
    - apt-get -y -qq update
    - apt-get -y -qq install build-essential mpich mpich-doc libmpich-dev libssl-dev
  script: make test
  tags:
    - shared runner




